# Generated by Django 5.0.2 on 2024-02-13 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OneTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThreeLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WordBattle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200, null=True)),
                ('category', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
