# Generated by Django 5.0.2 on 2024-02-14 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_attack_onetime_threeletter_wordbattle'),
    ]

    operations = [
        migrations.AddField(
            model_name='attack',
            name='next',
            field=models.IntegerField(null=True),
        ),
    ]
